name: K6 Teste de performance

on: [push]

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install K6
      run: |
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Run K6 Load Test
      run: k6 run load-test.js

    - name: Upload Load Test Results
      uses: actions/upload-artifact@v4
      with:
        name: load-test-result
        path: load-test-result.json
