name: K6 Teste de performance

on: [push]

jobs:
  k6-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Add K6 repository
      run: |
        wget -q -O - https://dl.k6.io/key.gpg | sudo gpg --dearmor -o /usr/share/keyrings/k6-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/k6-archive-keyring.gpg] https://dl.k6.io/deb stable main" | sudo tee /etc/apt/sources.list.d/k6.list > /dev/null

    - name: Install K6
      run: |
        sudo apt-get update
        sudo apt-get install -y k6

    - name: Run K6 Load Test
      run: k6 run load-test.js
      
    - name: Upload Load Test Results
      uses: actions/upload-artifact@v4
      with:
        name: load-test-result
        path: load-test-result.json
